export const PriceListData = [
  {
    season: "Letná mimosezóna",
    seasonDates: "1.6 - 30.6, 1.9 - 30.9",
    prices: [
      {
        lineOne: "min. 20 osôb",
        lineTwo: "min. 2 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "599€",
      },
      {
        lineOne: "min. 20 osôb",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "529€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 2 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "529€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "479€",
      },
    ],
  },
  {
    season: "Zimná mimosezóna",
    seasonDates: "4.1 - 31.5, 1.10 - 21.12",
    prices: [
      {
        lineOne: "min. 20 osôb",
        lineTwo: "min. 2 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "529€",
      },
      {
        lineOne: "min. 20 osôb",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "479€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 2 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "479€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "429€",
      },
    ],
  },
  {
    season: "Letná sezóna",
    seasonDates: "1.7 - 31.8",
    prices: [
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "579€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 4 noci",
        lineThree: "celý objekt",
        lineFour: null,
        time: "1 noc",
        price: "529€",
      },
    ],
  },
  {
    season: "Vianočný pobyt a Silvester",
    seasonDates: null,
    prices: [
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 3 noci",
        lineThree: "celý objekt",
        lineFour: "22.12 - 26.12",
        time: "1 noc",
        price: "599€",
      },
      {
        lineOne: "min. 1 osoba",
        lineTwo: "min. 4 noci",
        lineThree: "celý objekt",
        lineFour: "27.12 - 3.1",
        time: "1 noc",
        price: "749€",
      },
    ],
  },
];
